#ifndef XAYAH_FLUID_PBF_H
#define XAYAH_FLUID_PBF_H

#include "sph.h"

#include <cstdint>

namespace xayah::fluid::pbf::cuda_kernel {

    void launch_predict_forward(void* stream, std::uint32_t particle_count, float time_step, float gravity_x, float gravity_y, float gravity_z, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::ConstVector controls, sph::cuda_kernel::Vector predicted_positions);
    void launch_predict_jvp(void* stream, std::uint32_t particle_count, float time_step, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector velocity_tangent, sph::cuda_kernel::ConstVector control_tangent, sph::cuda_kernel::Vector predicted_position_tangent);
    void launch_predict_vjp(void* stream, std::uint32_t particle_count, float time_step, sph::cuda_kernel::ConstVectorAdjoint predicted_position_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint velocity_adjoint, sph::cuda_kernel::VectorAdjoint control_adjoint);

    void launch_lambda_forward(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* densities, const float* relaxation, sph::cuda_kernel::Vector gradient_sums, float* denominators, float* lambdas);
    void launch_lambda_jvp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::ParticleParameterTangent particle_tangent, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* densities, const float* density_tangent, const float* relaxation, const float* relaxation_tangent, sph::cuda_kernel::Vector gradient_sum_tangent, float* denominator_tangent, float* lambda_tangent);
    void launch_lambda_vjp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* densities, sph::cuda_kernel::ConstVector gradient_sums, const float* denominators, const double* lambda_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, double* density_adjoint, sph::cuda_kernel::ParticleParameterAdjoint particle_adjoint, double* relaxation_adjoint);

    void launch_correction_forward(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, sph::cuda_kernel::Vector corrections);
    void launch_correction_jvp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::ParticleParameterTangent particle_tangent, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* lambdas, const float* lambda_tangent, const float* artificial_pressure_strength, const float* artificial_pressure_strength_tangent, const float* artificial_pressure_exponent, const float* artificial_pressure_exponent_tangent, const float* artificial_pressure_radius, const float* artificial_pressure_radius_tangent, sph::cuda_kernel::Vector correction_tangent);
    void launch_correction_vjp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ParticleParameters particles, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Boundary boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, sph::cuda_kernel::ConstVectorAdjoint correction_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, double* lambda_adjoint, sph::cuda_kernel::ParticleParameterAdjoint particle_adjoint, double* artificial_pressure_strength_adjoint, double* artificial_pressure_exponent_adjoint, double* artificial_pressure_radius_adjoint);

    void launch_project_forward(void* stream, std::uint32_t particle_count, sph::cuda_kernel::Domain domain, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector corrections, std::uint32_t* collision_masks, sph::cuda_kernel::Vector projected_positions);
    void launch_project_jvp(void* stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector correction_tangent, sph::cuda_kernel::Vector projected_position_tangent);
    void launch_project_vjp(void* stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, sph::cuda_kernel::ConstVectorAdjoint projected_position_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint correction_adjoint);

    void launch_reconstruct_forward(void* stream, std::uint32_t particle_count, float inverse_time_step, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector corrected_positions, sph::cuda_kernel::Vector velocities);
    void launch_reconstruct_jvp(void* stream, std::uint32_t particle_count, float inverse_time_step, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector corrected_position_tangent, sph::cuda_kernel::Vector velocity_tangent);
    void launch_reconstruct_vjp(void* stream, std::uint32_t particle_count, float inverse_time_step, sph::cuda_kernel::ConstVectorAdjoint velocity_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint corrected_position_adjoint);

    void launch_vorticity_forward(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Vector vorticities);
    void launch_vorticity_jvp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector velocity_tangent, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::Vector vorticity_tangent);
    void launch_vorticity_vjp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::Neighborhood neighborhood, sph::cuda_kernel::ConstVectorAdjoint vorticity_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint velocity_adjoint);

    void launch_normal_forward(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::Neighborhood neighborhood, float* magnitudes, sph::cuda_kernel::Vector normals, float* normalizers);
    void launch_normal_jvp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector vorticity_tangent, sph::cuda_kernel::Neighborhood neighborhood, const float* magnitudes, sph::cuda_kernel::ConstVector normals, const float* normalizers, float* magnitude_tangent, sph::cuda_kernel::Vector normal_tangent);
    void launch_normal_vjp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::Neighborhood neighborhood, const float* magnitudes, sph::cuda_kernel::ConstVector normals, const float* normalizers, sph::cuda_kernel::ConstVectorAdjoint normal_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint vorticity_adjoint);

    void launch_confinement_forward(void* stream, std::uint32_t particle_count, float time_step, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::ConstVector normals, const float* confinement, sph::cuda_kernel::Vector confined_velocities);
    void launch_confinement_jvp(void* stream, std::uint32_t particle_count, float time_step, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::ConstVector normals, const float* confinement, sph::cuda_kernel::ConstVector velocity_tangent, sph::cuda_kernel::ConstVector vorticity_tangent, sph::cuda_kernel::ConstVector normal_tangent, const float* confinement_tangent, sph::cuda_kernel::Vector confined_velocity_tangent);
    void launch_confinement_vjp(void* stream, std::uint32_t particle_count, float time_step, sph::cuda_kernel::ConstVector vorticities, sph::cuda_kernel::ConstVector normals, const float* confinement, sph::cuda_kernel::ConstVectorAdjoint confined_velocity_adjoint, sph::cuda_kernel::VectorAdjoint velocity_adjoint, sph::cuda_kernel::VectorAdjoint vorticity_adjoint, sph::cuda_kernel::VectorAdjoint normal_adjoint, double* confinement_adjoint);

    void launch_xsph_forward(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::Neighborhood neighborhood, const float* viscosity, sph::cuda_kernel::Vector output_velocities);
    void launch_xsph_jvp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::ConstVector position_tangent, sph::cuda_kernel::ConstVector velocity_tangent, sph::cuda_kernel::Neighborhood neighborhood, const float* viscosity, const float* viscosity_tangent, sph::cuda_kernel::Vector output_velocity_tangent);
    void launch_xsph_vjp(void* stream, std::uint32_t particle_count, float support_radius, sph::cuda_kernel::ConstVector topology_positions, sph::cuda_kernel::ConstVector positions, sph::cuda_kernel::ConstVector velocities, sph::cuda_kernel::Neighborhood neighborhood, const float* viscosity, sph::cuda_kernel::ConstVectorAdjoint output_velocity_adjoint, sph::cuda_kernel::VectorAdjoint position_adjoint, sph::cuda_kernel::VectorAdjoint velocity_adjoint, double* viscosity_adjoint);

} // namespace xayah::fluid::pbf::cuda_kernel

#endif
